documentation:
  - "**/*.md"
  - "docs/**/*"
  - "website/**/*"
examples:
  - "examples/**/*"
github-actions:
  - ".github/*.yml"
  - ".github/workflows/*.yml"
terraform:
  - "**/*.tf"
ci/cd:
  - .github/workflows/*
