---
on:
  - pull_request_target
name: Pull Request Target (All types)
env:
  IN_MAINTAINER_LIST: ${{ contains(secrets.MAINTAINER_LIST, github.actor) }}

jobs:
  Labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Apply Labels
        uses: actions/labeler@v4
        with:
          configuration-path: .github/labeler-pr-triage.yaml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  NeedsTriageLabeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Apply needs-triage Label
        uses: actions/labeler@v4
        if: github.event.action == 'opened' && env.IN_MAINTAINER_LIST == 'false'
        with:
          configuration-path: .github/labeler-pr-needs-triage.yaml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  SizeLabeler:
    runs-on: ubuntu-latest
    steps:
      - name: Apply Size Label
        uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: "size/XS"
          xs_max_size: "30"
          s_label: "size/S"
          s_max_size: "60"
          m_label: "size/M"
          m_max_size: "150"
          l_label: "size/L"
          l_max_size: "300"
          xl_label: "size/XL"
          fail_if_xl: "false"
          message_if_xl: >
            This PR exceeds the recommended size of 1000 lines.
            Please make sure you are NOT addressing multiple issues with one PR.
            Note this PR might be rejected due to its size.
  PullRequestComments:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to add helpful context for new contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |-
            Welcome @${{github.actor}} :wave:

            Thanks again, and welcome to the community! :smiley:
